services:
  - type: web
    name: esg-dashboard
    runtime: python
    buildCommand: ""
    startCommand: gunicorn esg_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: esg_project.settings
      - key: PYTHON_VERSION
        value: 3.11
